
#spring.jpa.show-sql: true

#jpa configurations




#
#spring.servlet.multipart.enabled=true
#spring.servlet.multipart.max-file-size=2MB
#spring.servlet.multipart.max-request-size=2MB

#spring.mvc.view.prefix=/
#spring.mvc.view.suffix=.jsp


spring.profiles.active=${ENV:dev}